# Train gradient boosting model

# 1. Imports

## 1.1 Packages

In [2]:
import sys

import pandas as pd

## 1.2 Options

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
sys.path.append('../src/velib_prediction/pipelines')

In [5]:
from train_model.nodes import get_split_train_val_cv

## 1.3 Datasets

In [6]:
df_train = pd.read_parquet("../data/04_feature/df_feat_train.parquet")
df_train.sample(2)

,stationcode,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,code_insee_commune,date,duedate_year,duedate_month,duedate_day,duedate_weekday,duedate_weekend
261,44010,0,30.0,30,0,0,0,0,0,2023-11-05 08:56:42,94081,2023-11-05,2023,11,5,6,1
1351,16501,1,25.0,25,0,0,0,0,0,2024-08-10 20:44:26,75056,2024-08-10,2024,8,10,5,1

In [10]:
df_train.sort_values(by=["stationcode", "duedate"]).tail(10)

,stationcode,is_installed,capacity,numdocksavailable,numbikesavailable,mechanical,ebike,is_renting,is_returning,duedate,code_insee_commune,date,duedate_year,duedate_month,duedate_day,duedate_weekday,duedate_weekend
121,43401,1,45.0,45,0,0,0,0,0,2024-06-24 17:05:58,94042,2024-06-24,2024,6,24,0,0
261,44010,0,30.0,30,0,0,0,0,0,2023-11-05 08:56:42,94081,2023-11-05,2023,11,5,6,1
1443,47006,1,16.0,16,0,0,0,0,0,2024-06-30 14:15:51,94046,2024-06-30,2024,6,30,6,1
1363,5201,1,16.0,16,0,0,0,0,0,2024-05-29 18:22:19,75056,2024-05-29,2024,5,29,2,0
1371,7201,0,0.0,0,0,0,0,0,0,2024-04-26 16:47:44,75056,2024-04-26,2024,4,26,4,0
1349,7500,1,15.0,15,0,0,0,0,0,2024-08-08 15:10:16,75056,2024-08-08,2024,8,8,3,0
853,8116,1,25.0,25,0,0,0,0,0,2021-02-21 19:09:18,75056,2021-02-21,2021,2,21,6,1
1329,8500,1,15.0,15,0,0,0,0,0,2024-08-12 09:58:47,75056,2024-08-12,2024,8,12,0,0
1471,8501,1,23.0,23,0,0,0,0,0,2024-08-11 11:48:45,75056,2024-08-11,2024,8,11,6,1
998,9037,1,24.0,24,0,0,0,0,0,2023-10-01 22:05:20,75056,2023-10-01,2023,10,1,6,1

# 2. Prepare datasets

In [ ]:
list_df = get_split_train_val_cv(df_train, n_splits=3)

In [ ]:
len(list_df)

3